version: '3.7'

services:
  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./app:/app
    ports:
      - 8001:8001
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=website_content
    expose: 
      - 5432

volumes:
  postgres_data: