version: '3.7'

services:
  fastapi:
    build: ./fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./fastapi:/app
    ports:
      - 8001:8001
    environment:
      - DB_CONNECTION=postgresql://postgres:1@db:5432/website_content
    depends_on:
      - db
    
  crawler:
    build: ./crawler
    command: scrapy runspider url_spider.py -o url.json
    volumes:
      - ./crawler:/app
    environment:
      - DB_CONNECTION=postgresql://postgres:1@db:5432/website_content
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=website_content
    ports: 
      - 6543:5432

volumes:
  postgres_data: